name: Build and Publish Arkeo Data Engine (Subscriber) Docker image

on:
  push:
    branches: ["main"]
    paths:
      - "subscriber-core/**"
      - ".github/workflows/arkeo-data-engine-subscriber-docker.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "subscriber-core/**"
      - ".github/workflows/arkeo-data-engine-subscriber-docker.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push arkeo-data-engine-subscriber image
        uses: docker/build-push-action@v6
        with:
          context: ./subscriber-core
          file: ./subscriber-core/Dockerfile
          push: ${{ github.event_name == 'push' }}
          build-args: |
            APP_VERSION=${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.sha }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/arkeo-data-engine-subscriber:latest
            ghcr.io/${{ github.repository_owner }}/arkeo-data-engine-subscriber:${{ github.sha }}
